// <auto-generated />
using Bazaar.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bazaar.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240604145012_AddProductData")]
    partial class AddProductData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bazaar.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("Bazaar.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Bilbo Baggins",
                            Description = "Dive into the narrative as Bilbo embarks on a quest that transforms him from a comfort-loving hobbit into an unlikely hero. The story is interwoven with suspense, humor, and vivid descriptions that bring to life the world of Middle-earth. There and Back Again is not just a book; it's an invitation to adventure, friendship, and the discovery of one's own potential ",
                            ISBN = "SWD9999001",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "There and back again"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Eddard Stark",
                            Description = "Eddard Stark captures the essence of duty, integrity, and sacrifice that defines the Warden of the North. Through vivid storytelling and rich character exploration, readers are transported to the heart of Winterfell and the stark realities of power and loyalty in the Seven Kingdoms. This book is a tribute to the steadfastness of Eddard Stark, illustrating his unwavering commitment to justice and family amidst a world of political intrigue and betrayal.",
                            ISBN = "CAW777777701",
                            ListPrice = 40.0,
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Honor"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Samwise Gamgee ",
                            Description = "Potatoes is a celebration of one of the Shire's most beloved staples, featuring a treasure trove of mouthwatering recipes and cooking tips. Whether you prefer them mashed, roasted, or fried, Samwise has something for everyone in this comprehensive guide to potato perfection. Join him as he shares anecdotes from his time in the kitchen and imparts the wisdom passed down from generations of hobbit cooks. With Potatoes in hand, you'll never look at this humble tuber the same way again. ",
                            ISBN = "RITO5555501",
                            ListPrice = 55.0,
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Potatoes"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Arya Stark",
                            Description = "How to Survive Outside is your ultimate companion for mastering the skills needed to thrive beyond the safety of city walls. From finding food and shelter to evading danger and honing your combat abilities, Arya Stark provides practical advice and cunning strategies gleaned from her own adventures across Westeros and beyond. Whether you're a seasoned explorer or a novice venturing into the unknown, this indispensable manual will equip you with the knowledge and confidence to conquer any wilderness. ",
                            ISBN = "WS3333333301",
                            ListPrice = 70.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "How to survive outside"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Gandalf the Grey",
                            Description = "Embark on a fantastical journey through the realms of Middle-earth with Magical Creatures of Middle - earth by the venerable Gandalf the Grey. In this enchanting compendium, Gandalf unveils the wondrous creatures that inhabit Tolkien's richly imagined world, from noble ents and mischievous hobbits to fearsome dragons and elusive unicorns. With captivating illustrations and insightful commentary, this definitive guide offers a rare glimpse into the fauna of Middle-earth, making it a must-have for fans of fantasy and folklore alike.",
                            ISBN = "SOTJ1111111101",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Magical Creatures of Middle-earth"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Tyrion Lannister",
                            Description = "Delve into the intricate world of politics and negotiation with The Art of Diplomacy by the cunning Tyrion Lannister. In this masterful treatise, Tyrion shares his unparalleled expertise on the delicate dance of power and persuasion, offering timeless lessons on diplomacy and statecraft gleaned from his own exploits in the corridors of King's Landing and beyond. Whether you aspire to navigate the treacherous waters of court intrigue or simply seek to understand the machinations of power, this insightful guide is an indispensable resource for any aspiring diplomat or seasoned ruler.",
                            ISBN = "FOT000000001",
                            ListPrice = 25.0,
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Title = "The Art of Diplomacy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
